"""Add mode

Revision ID: ef1a0c2ed135
Revises: 
Create Date: 2025-04-26 18:34:28.299466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1a0c2ed135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streak', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mode', sa.Enum('Normal', 'Hard', name='mode'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streak', schema=None) as batch_op:
        batch_op.drop_column('Mode')

    # ### end Alembic commands ###
